KVERSION ?= 7.2.6-1-liquorix-amd64
KDIR     ?= /lib/modules/$(KVERSION)/build
PWD      := $(shell pwd)

obj-m    += src/kernel/fabriczc_mod.o
src/kernel/fabriczc_mod-y := src/kernel/main.o

all:
	$(MAKE) -C $(KDIR) M=$(PWD) modules
	$(CC) -Wall -Wextra -O3 src/user/control.c -o src/user/fabriczc_ctl

clean:
	$(MAKE) -C $(KDIR) M=$(PWD) clean
	rm -f src/user/fabriczc_ctl
	@rm -f src/kernel/.*.cmd src/kernel/*.o src/kernel/*.ko src/kernel/*.mod*
